version: "3.8"
services:
  sonarqube:
    image: jarnoweemen/auctionsense:sonarqube-auctionsense
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - sonarqube-db
    ports:
      - "9000:9000"
    networks:
      - auctionsense_sonarqube
  sonarqube-db:
    image: jarnoweemen/auctionsense:sonarqube-db-auctionsense
    hostname: postgresql
    container_name: sonarqube-db
    networks:
      - auctionsense_sonarqube

networks:
  auctionsense_sonarqube:
    driver: bridge